/* eslint-disable camelcase */
import {HDate, greg, Locale, gematriya} from '@hebcal/core';
import {throwTypeError} from './throwTypeError';

// On 9 July 2020 all three tracks completed the Rambam learning cycle.
// The 3 chapter daily track completed its 39th cycle while the one chapter
// daily track completed its 13th.
// https://en.wikipedia.org/wiki/Daily_Rambam_Study

const cycleLen = 1016;

// The cycle of Rambam began on Sunday, 27 Nissan, 5744 - Apr. 29, 1984.
const startDate = new Date(1984, 3, 29);
export const rambam1StartAbs = greg.greg2abs(startDate);

const mishnehTorah = [
  ['Transmission of the Oral Law', 3],
  ['Positive Mitzvot', 3],
  ['Negative Mitzvot', 3],
  ['Overview of Mishneh Torah Contents', 3],
  ['Foundations of the Torah', 10],
  ['Human Dispositions', 7],
  ['Torah Study', 7],
  ['Foreign Worship and Customs of the Nations', 12],
  ['Repentance', 10],
  ['Reading the Shema', 4],
  ['Prayer and the Priestly Blessing', 15],
  ['Tefillin, Mezuzah and the Torah Scroll', 10],
  ['Fringes', 3],
  ['Blessings', 11],
  ['Circumcision', 3],
  ['The Order of Prayer', 4],
  ['Sabbath', 30],
  ['Eruvin', 8],
  ['Rest on the Tenth of Tishrei', 3],
  ['Rest on a Holiday', 8],
  ['Leavened and Unleavened Bread', 9],
  ['Shofar, Sukkah and Lulav', 8],
  ['Sheqel Dues', 4],
  ['Sanctification of the New Month', 19],
  ['Fasts', 5],
  ['Scroll of Esther and Hanukkah', 4],
  ['Marriage', 25],
  ['Divorce', 13],
  ['Levirate Marriage and Release', 8],
  ['Virgin Maiden', 3],
  ['Woman Suspected of Infidelity', 4],
  ['Forbidden Intercourse', 22],
  ['Forbidden Foods', 17],
  ['Ritual Slaughter', 14],
  ['Oaths', 12],
  ['Vows', 13],
  ['Nazariteship', 10],
  ['Appraisals and Devoted Property', 8],
  ['Diverse Species', 10],
  ['Gifts to the Poor', 10],
  ['Heave Offerings', 15],
  ['Tithes', 14],
  ['Second Tithes and Fourth Year\'s Fruit', 11],
  ['First Fruits and other Gifts to Priests Outside the Sanctuary', 12],
  ['Sabbatical Year and the Jubilee', 13],
  ['The Chosen Temple', 8],
  ['Vessels of the Sanctuary and Those who Serve Therein', 10],
  ['Admission into the Sanctuary', 9],
  ['Things Forbidden on the Altar', 7],
  ['Sacrificial Procedure', 19],
  ['Daily Offerings and Additional Offerings', 10],
  ['Sacrifices Rendered Unfit', 19],
  ['Service on the Day of Atonement', 5],
  ['Trespass', 8],
  ['Paschal Offering', 10],
  ['Festival Offering', 3],
  ['Firstlings', 8],
  ['Offerings for Unintentional Transgressions', 15],
  ['Offerings for Those with Incomplete Atonement', 5],
  ['Substitution', 4],
  ['Defilement by a Corpse', 25],
  ['Red Heifer', 15],
  ['Defilement by Leprosy', 16],
  ['Those Who Defile Bed or Seat', 13],
  ['Other Sources of Defilement', 20],
  ['Defilement of Foods', 16],
  ['Vessels', 28],
  ['Immersion Pools', 11],
  ['Damages to Property', 14],
  ['Theft', 9],
  ['Robbery and Lost Property', 18],
  ['One Who Injures a Person or Property', 8],
  ['Murderer and the Preservation of Life', 13],
  ['Sales', 30],
  ['Ownerless Property and Gifts', 12],
  ['Neighbors', 14],
  ['Agents and Partners', 10],
  ['Slaves', 9],
  ['Hiring', 13],
  ['Borrowing and Deposit', 8],
  ['Creditor and Debtor', 27],
  ['Plaintiff and Defendant', 16],
  ['Inheritances', 11],
  ['The Sanhedrin and the Penalties within their Jurisdiction', 26],
  ['Testimony', 22],
  ['Rebels', 7],
  ['Mourning', 14],
  ['Kings and Wars', 12],
].map((m) => {
  return {name: m[0], ch: m[1]};
});

const first4verses = [
  ['1-21', '22-33', '34-45'], // Transmission of the Oral Law
  ['1-83', '84-166', '167-248'], // Positive Mitzvot
  ['1-122', '123-245', '246-365'], // Negative Mitzvot
  ['1:1-4:8', '5:1-9:9', '10:1-14:10'], // Overview of Mishneh Torah Contents
];

/**
 * Calculates Daily Rambam (Mishneh Torah) for 1 chapter a day cycle.
 * @param {HDate|Date|number} date - Hebrew or Gregorian date
 * @return {any}
 */
export function dailyRambam1(date) {
  const cday = (typeof date === 'number' && !isNaN(date)) ? date :
    greg.isDate(date) ? greg.greg2abs(date) :
    HDate.isHDate(date) ? date.abs() :
    throwTypeError(`non-date given to dailyRambam: ${date}`);
  if (cday < rambam1StartAbs) {
    throw new RangeError(`Date ${date} too early; Daily Rambam cycle began on ${startDate}`);
  }
  const dno = (cday - rambam1StartAbs) % cycleLen;
  let total = 0;
  let chapNum = 0;
  let sectionNum = -1;
  let j = 0;
  const numSections = mishnehTorah.length;
  while (j < numSections) {
    sectionNum++;
    total = total + mishnehTorah[j].ch - 1;
    if (dno < total) {
      chapNum = (mishnehTorah[j].ch + 1) - (total - dno);
      // Bailout
      j = 1 + numSections;
    }
    j++;
  }
  const perek = sectionNum < 4 ? first4verses[sectionNum][chapNum - 1] : chapNum;
  return {name: mishnehTorah[sectionNum].name, perek};
}

/**
 * Event wrapper around a Daily Rambam instance
 */
export class DailyRambamEvent extends Event {
  /**
   * @param {HDate} date
   * @param {any} reading
   */
  constructor(date, reading) {
    super(date, `${reading.name} ${reading.perek}`, flags.USER_EVENT);
    this.reading = reading;
    this.memo = this.render('memo');
    this.alarm = false;
    this.category = 'Daily Rambam';
  }
  /**
   * Returns name of reading
   * @param {string} [locale] Optional locale name (defaults to active locale).
   * @return {string}
   */
  render(locale) {
    locale = locale || Locale.getLocaleName();
    if (typeof locale === 'string') {
      locale = locale.toLowerCase();
    }
    const reading = this.reading;
    if ((locale === 'he' || locale === 'he-x-nonikud') && typeof reading.perek === 'number') {
      return Locale.gettext(reading.name, locale) + ' פרק ' +
        gematriya(reading.perek);
    }
    return Locale.gettext(reading.name, locale) + ' ' + reading.perek;
  }
  /**
   * Returns a link to sefaria.org
   * @return {string}
   */
  url() {
    const reading = this.reading;
    const name = 'Mishneh Torah, ' + reading.name + '.' + reading.perek;
    const urlName = encodeURIComponent(name.replace(/ /g, '_').replace(/:/g, '.'));
    return `https://www.sefaria.org/${urlName}?lang=bi`;
  }
  /** @return {string[]} */
  getCategories() {
    return ['dailyRambam1'];
  }
}

const Transmission_of_the_Oral_Law = 'Transmission of the Oral Law';
const Positive_Mitzvot = 'Positive Mitzvot';
const Negative_Mitzvot = 'Negative Mitzvot';
const Overview_of_Mishneh_Torah_Contents = 'Overview of Mishneh Torah Contents';
const Foundations_of_the_Torah = 'Foundations of the Torah';
const Human_Dispositions = 'Human Dispositions';
const Torah_Study = 'Torah Study';
const Foreign_Worship_and_Customs_of_the_Nations = 'Foreign Worship and Customs of the Nations';
const Repentance = 'Repentance';
const Reading_the_Shema = 'Reading the Shema';
const Prayer_and_the_Priestly_Blessing = 'Prayer and the Priestly Blessing';
const Tefillin_Mezuzah_and_the_Torah_Scroll = 'Tefillin, Mezuzah and the Torah Scroll';
const Fringes = 'Fringes';
const Blessings = 'Blessings';
const Circumcision = 'Circumcision';
const The_Order_of_Prayer = 'The Order of Prayer';
const Sabbath = 'Sabbath';
const Eruvin = 'Eruvin';
const Rest_on_the_Tenth_of_Tishrei = 'Rest on the Tenth of Tishrei';
const Rest_on_a_Holiday = 'Rest on a Holiday';
const Leavened_and_Unleavened_Bread = 'Leavened and Unleavened Bread';
const Shofar_Sukkah_and_Lulav = 'Shofar, Sukkah and Lulav';
const Sheqel_Dues = 'Sheqel Dues';
const Sanctification_of_the_New_Month = 'Sanctification of the New Month';
const Fasts = 'Fasts';
const Scroll_of_Esther_and_Hanukkah = 'Scroll of Esther and Hanukkah';
const Marriage = 'Marriage';
const Divorce = 'Divorce';
const Levirate_Marriage_and_Release = 'Levirate Marriage and Release';
const Virgin_Maiden = 'Virgin Maiden';
const Woman_Suspected_of_Infidelity = 'Woman Suspected of Infidelity';
const Forbidden_Intercourse = 'Forbidden Intercourse';
const Forbidden_Foods = 'Forbidden Foods';
const Ritual_Slaughter = 'Ritual Slaughter';
const Oaths = 'Oaths';
const Vows = 'Vows';
const Nazariteship = 'Nazariteship';
const Appraisals_and_Devoted_Property = 'Appraisals and Devoted Property';
const Diverse_Species = 'Diverse Species';
const Gifts_to_the_Poor = 'Gifts to the Poor';
const Heave_Offerings = 'Heave Offerings';
const Tithes = 'Tithes';
const Second_Tithes_and_Fourth_Year_s_Fruit = 'Second Tithes and Fourth Year\'s Fruit';
const First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary = 'First Fruits and other Gifts to Priests Outside the Sanctuary';
const Sabbatical_Year_and_the_Jubilee = 'Sabbatical Year and the Jubilee';
const The_Chosen_Temple = 'The Chosen Temple';
const Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein = 'Vessels of the Sanctuary and Those who Serve Therein';
const Admission_into_the_Sanctuary = 'Admission into the Sanctuary';
const Things_Forbidden_on_the_Altar = 'Things Forbidden on the Altar';
const Sacrificial_Procedure = 'Sacrificial Procedure';
const Daily_Offerings_and_Additional_Offerings = 'Daily Offerings and Additional Offerings';
const Sacrifices_Rendered_Unfit = 'Sacrifices Rendered Unfit';
const Service_on_the_Day_of_Atonement = 'Service on the Day of Atonement';
const Trespass = 'Trespass';
const Paschal_Offering = 'Paschal Offering';
const Festival_Offering = 'Festival Offering';
const Firstlings = 'Firstlings';
const Offerings_for_Unintentional_Transgressions = 'Offerings for Unintentional Transgressions';
const Offerings_for_Those_with_Incomplete_Atonement = 'Offerings for Those with Incomplete Atonement';
const Substitution = 'Substitution';
const Defilement_by_a_Corpse = 'Defilement by a Corpse';
const Red_Heifer = 'Red Heifer';
const Defilement_by_Leprosy = 'Defilement by Leprosy';
const Those_Who_Defile_Bed_or_Seat = 'Those Who Defile Bed or Seat';
const Other_Sources_of_Defilement = 'Other Sources of Defilement';
const Defilement_of_Foods = 'Defilement of Foods';
const Vessels = 'Vessels';
const Immersion_Pools = 'Immersion Pools';
const Damages_to_Property = 'Damages to Property';
const Theft = 'Theft';
const Robbery_and_Lost_Property = 'Robbery and Lost Property';
const One_Who_Injures_a_Person_or_Property = 'One Who Injures a Person or Property';
const Murderer_and_the_Preservation_of_Life = 'Murderer and the Preservation of Life';
const Sales = 'Sales';
const Ownerless_Property_and_Gifts = 'Ownerless Property and Gifts';
const Neighbors = 'Neighbors';
const Agents_and_Partners = 'Agents and Partners';
const Slaves = 'Slaves';
const Hiring = 'Hiring';
const Borrowing_and_Deposit = 'Borrowing and Deposit';
const Creditor_and_Debtor = 'Creditor and Debtor';
const Plaintiff_and_Defendant = 'Plaintiff and Defendant';
const Inheritances = 'Inheritances';
const The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction = 'The Sanhedrin and the Penalties within their Jurisdiction';
const Testimony = 'Testimony';
const Rebels = 'Rebels';
const Mourning = 'Mourning';
const Kings_and_Wars = 'Kings and Wars';

export const arr = [
  [Transmission_of_the_Oral_Law, '1-21'],
  [Transmission_of_the_Oral_Law, '22-33'],
  [Transmission_of_the_Oral_Law, '34-45'],
  [Positive_Mitzvot, '1-83'],
  [Positive_Mitzvot, '84-166'],
  [Positive_Mitzvot, '167-248'],
  [Negative_Mitzvot, '1-122'],
  [Negative_Mitzvot, '123-245'],
  [Negative_Mitzvot, '246-365'],
  [Overview_of_Mishneh_Torah_Contents, '1:1-4:8'],
  [Overview_of_Mishneh_Torah_Contents, '5:1-9:9'],
  [Overview_of_Mishneh_Torah_Contents, '10:1-14:10'],
  [Foundations_of_the_Torah, 1],
  [Foundations_of_the_Torah, 2],
  [Foundations_of_the_Torah, 3],
  [Foundations_of_the_Torah, 4],
  [Foundations_of_the_Torah, 5],
  [Foundations_of_the_Torah, 6],
  [Foundations_of_the_Torah, 7],
  [Foundations_of_the_Torah, 8],
  [Foundations_of_the_Torah, 9],
  [Foundations_of_the_Torah, 10],
  [Human_Dispositions, 1],
  [Human_Dispositions, 2],
  [Human_Dispositions, 3],
  [Human_Dispositions, 4],
  [Human_Dispositions, 5],
  [Human_Dispositions, 6],
  [Human_Dispositions, 7],
  [Torah_Study, 1],
  [Torah_Study, 2],
  [Torah_Study, 3],
  [Torah_Study, 4],
  [Torah_Study, 5],
  [Torah_Study, 6],
  [Torah_Study, 7],
  [Foreign_Worship_and_Customs_of_the_Nations, 1],
  [Foreign_Worship_and_Customs_of_the_Nations, 2],
  [Foreign_Worship_and_Customs_of_the_Nations, 3],
  [Foreign_Worship_and_Customs_of_the_Nations, 4],
  [Foreign_Worship_and_Customs_of_the_Nations, 5],
  [Foreign_Worship_and_Customs_of_the_Nations, 6],
  [Foreign_Worship_and_Customs_of_the_Nations, 7],
  [Foreign_Worship_and_Customs_of_the_Nations, 8],
  [Foreign_Worship_and_Customs_of_the_Nations, 9],
  [Foreign_Worship_and_Customs_of_the_Nations, 10],
  [Foreign_Worship_and_Customs_of_the_Nations, 11],
  [Foreign_Worship_and_Customs_of_the_Nations, 12],
  [Repentance, 1],
  [Repentance, 2],
  [Repentance, 3],
  [Repentance, 4],
  [Repentance, 5],
  [Repentance, 6],
  [Repentance, 7],
  [Repentance, 8],
  [Repentance, 9],
  [Repentance, 10],
  [Reading_the_Shema, 1],
  [Reading_the_Shema, 2],
  [Reading_the_Shema, 3],
  [Reading_the_Shema, 4],
  [Prayer_and_the_Priestly_Blessing, 1],
  [Prayer_and_the_Priestly_Blessing, 2],
  [Prayer_and_the_Priestly_Blessing, 3],
  [Prayer_and_the_Priestly_Blessing, 4],
  [Prayer_and_the_Priestly_Blessing, 5],
  [Prayer_and_the_Priestly_Blessing, 6],
  [Prayer_and_the_Priestly_Blessing, 7],
  [Prayer_and_the_Priestly_Blessing, 8],
  [Prayer_and_the_Priestly_Blessing, 9],
  [Prayer_and_the_Priestly_Blessing, 10],
  [Prayer_and_the_Priestly_Blessing, 11],
  [Prayer_and_the_Priestly_Blessing, 12],
  [Prayer_and_the_Priestly_Blessing, 13],
  [Prayer_and_the_Priestly_Blessing, 14],
  [Prayer_and_the_Priestly_Blessing, 15],
  [Tefillin_Mezuzah_and_the_Torah_Scroll, 1],
  [Tefillin_Mezuzah_and_the_Torah_Scroll, 2],
  [Tefillin_Mezuzah_and_the_Torah_Scroll, 3],
  [Tefillin_Mezuzah_and_the_Torah_Scroll, 4],
  [Tefillin_Mezuzah_and_the_Torah_Scroll, 5],
  [Tefillin_Mezuzah_and_the_Torah_Scroll, 6],
  [Tefillin_Mezuzah_and_the_Torah_Scroll, 7],
  [Tefillin_Mezuzah_and_the_Torah_Scroll, 8],
  [Tefillin_Mezuzah_and_the_Torah_Scroll, 9],
  [Tefillin_Mezuzah_and_the_Torah_Scroll, 10],
  [Fringes, 1],
  [Fringes, 2],
  [Fringes, 3],
  [Blessings, 1],
  [Blessings, 2],
  [Blessings, 3],
  [Blessings, 4],
  [Blessings, 5],
  [Blessings, 6],
  [Blessings, 7],
  [Blessings, 8],
  [Blessings, 9],
  [Blessings, 10],
  [Blessings, 11],
  [Circumcision, 1],
  [Circumcision, 2],
  [Circumcision, 3],
  [The_Order_of_Prayer, 1],
  [The_Order_of_Prayer, 2],
  [The_Order_of_Prayer, 3],
  [The_Order_of_Prayer, 4],
  [Sabbath, 1],
  [Sabbath, 2],
  [Sabbath, 3],
  [Sabbath, 4],
  [Sabbath, 5],
  [Sabbath, 6],
  [Sabbath, 7],
  [Sabbath, 8],
  [Sabbath, 9],
  [Sabbath, 10],
  [Sabbath, 11],
  [Sabbath, 12],
  [Sabbath, 13],
  [Sabbath, 14],
  [Sabbath, 15],
  [Sabbath, 16],
  [Sabbath, 17],
  [Sabbath, 18],
  [Sabbath, 19],
  [Sabbath, 20],
  [Sabbath, 21],
  [Sabbath, 22],
  [Sabbath, 23],
  [Sabbath, 24],
  [Sabbath, 25],
  [Sabbath, 26],
  [Sabbath, 27],
  [Sabbath, 28],
  [Sabbath, 29],
  [Sabbath, 30],
  [Eruvin, 1],
  [Eruvin, 2],
  [Eruvin, 3],
  [Eruvin, 4],
  [Eruvin, 5],
  [Eruvin, 6],
  [Eruvin, 7],
  [Eruvin, 8],
  [Rest_on_the_Tenth_of_Tishrei, 1],
  [Rest_on_the_Tenth_of_Tishrei, 2],
  [Rest_on_the_Tenth_of_Tishrei, 3],
  [Rest_on_a_Holiday, 1],
  [Rest_on_a_Holiday, 2],
  [Rest_on_a_Holiday, 3],
  [Rest_on_a_Holiday, 4],
  [Rest_on_a_Holiday, 5],
  [Rest_on_a_Holiday, 6],
  [Rest_on_a_Holiday, 7],
  [Rest_on_a_Holiday, 8],
  [Leavened_and_Unleavened_Bread, 1],
  [Leavened_and_Unleavened_Bread, 2],
  [Leavened_and_Unleavened_Bread, 3],
  [Leavened_and_Unleavened_Bread, 4],
  [Leavened_and_Unleavened_Bread, 5],
  [Leavened_and_Unleavened_Bread, 6],
  [Leavened_and_Unleavened_Bread, 7],
  [Leavened_and_Unleavened_Bread, 8],
  [Leavened_and_Unleavened_Bread, 9],
  [Shofar_Sukkah_and_Lulav, 1],
  [Shofar_Sukkah_and_Lulav, 2],
  [Shofar_Sukkah_and_Lulav, 3],
  [Shofar_Sukkah_and_Lulav, 4],
  [Shofar_Sukkah_and_Lulav, 5],
  [Shofar_Sukkah_and_Lulav, 6],
  [Shofar_Sukkah_and_Lulav, 7],
  [Shofar_Sukkah_and_Lulav, 8],
  [Sheqel_Dues, 1],
  [Sheqel_Dues, 2],
  [Sheqel_Dues, 3],
  [Sheqel_Dues, 4],
  [Sanctification_of_the_New_Month, 1],
  [Sanctification_of_the_New_Month, 2],
  [Sanctification_of_the_New_Month, 3],
  [Sanctification_of_the_New_Month, 4],
  [Sanctification_of_the_New_Month, 5],
  [Sanctification_of_the_New_Month, 6],
  [Sanctification_of_the_New_Month, 7],
  [Sanctification_of_the_New_Month, 8],
  [Sanctification_of_the_New_Month, 9],
  [Sanctification_of_the_New_Month, 10],
  [Sanctification_of_the_New_Month, 11],
  [Sanctification_of_the_New_Month, 12],
  [Sanctification_of_the_New_Month, 13],
  [Sanctification_of_the_New_Month, 14],
  [Sanctification_of_the_New_Month, 15],
  [Sanctification_of_the_New_Month, 16],
  [Sanctification_of_the_New_Month, 17],
  [Sanctification_of_the_New_Month, 18],
  [Sanctification_of_the_New_Month, 19],
  [Fasts, 1],
  [Fasts, 2],
  [Fasts, 3],
  [Fasts, 4],
  [Fasts, 5],
  [Scroll_of_Esther_and_Hanukkah, 1],
  [Scroll_of_Esther_and_Hanukkah, 2],
  [Scroll_of_Esther_and_Hanukkah, 3],
  [Scroll_of_Esther_and_Hanukkah, 4],
  [Marriage, 1],
  [Marriage, 2],
  [Marriage, 3],
  [Marriage, 4],
  [Marriage, 5],
  [Marriage, 6],
  [Marriage, 7],
  [Marriage, 8],
  [Marriage, 9],
  [Marriage, 10],
  [Marriage, 11],
  [Marriage, 12],
  [Marriage, 13],
  [Marriage, 14],
  [Marriage, 15],
  [Marriage, 16],
  [Marriage, 17],
  [Marriage, 18],
  [Marriage, 19],
  [Marriage, 20],
  [Marriage, 21],
  [Marriage, 22],
  [Marriage, 23],
  [Marriage, 24],
  [Marriage, 25],
  [Divorce, 1],
  [Divorce, 2],
  [Divorce, 3],
  [Divorce, 4],
  [Divorce, 5],
  [Divorce, 6],
  [Divorce, 7],
  [Divorce, 8],
  [Divorce, 9],
  [Divorce, 10],
  [Divorce, 11],
  [Divorce, 12],
  [Divorce, 13],
  [Levirate_Marriage_and_Release, 1],
  [Levirate_Marriage_and_Release, 2],
  [Levirate_Marriage_and_Release, 3],
  [Levirate_Marriage_and_Release, 4],
  [Levirate_Marriage_and_Release, 5],
  [Levirate_Marriage_and_Release, 6],
  [Levirate_Marriage_and_Release, 7],
  [Levirate_Marriage_and_Release, 8],
  [Virgin_Maiden, 1],
  [Virgin_Maiden, 2],
  [Virgin_Maiden, 3],
  [Woman_Suspected_of_Infidelity, 1],
  [Woman_Suspected_of_Infidelity, 2],
  [Woman_Suspected_of_Infidelity, 3],
  [Woman_Suspected_of_Infidelity, 4],
  [Forbidden_Intercourse, 1],
  [Forbidden_Intercourse, 2],
  [Forbidden_Intercourse, 3],
  [Forbidden_Intercourse, 4],
  [Forbidden_Intercourse, 5],
  [Forbidden_Intercourse, 6],
  [Forbidden_Intercourse, 7],
  [Forbidden_Intercourse, 8],
  [Forbidden_Intercourse, 9],
  [Forbidden_Intercourse, 10],
  [Forbidden_Intercourse, 11],
  [Forbidden_Intercourse, 12],
  [Forbidden_Intercourse, 13],
  [Forbidden_Intercourse, 14],
  [Forbidden_Intercourse, 15],
  [Forbidden_Intercourse, 16],
  [Forbidden_Intercourse, 17],
  [Forbidden_Intercourse, 18],
  [Forbidden_Intercourse, 19],
  [Forbidden_Intercourse, 20],
  [Forbidden_Intercourse, 21],
  [Forbidden_Intercourse, 22],
  [Forbidden_Foods, 1],
  [Forbidden_Foods, 2],
  [Forbidden_Foods, 3],
  [Forbidden_Foods, 4],
  [Forbidden_Foods, 5],
  [Forbidden_Foods, 6],
  [Forbidden_Foods, 7],
  [Forbidden_Foods, 8],
  [Forbidden_Foods, 9],
  [Forbidden_Foods, 10],
  [Forbidden_Foods, 11],
  [Forbidden_Foods, 12],
  [Forbidden_Foods, 13],
  [Forbidden_Foods, 14],
  [Forbidden_Foods, 15],
  [Forbidden_Foods, 16],
  [Forbidden_Foods, 17],
  [Ritual_Slaughter, 1],
  [Ritual_Slaughter, 2],
  [Ritual_Slaughter, 3],
  [Ritual_Slaughter, 4],
  [Ritual_Slaughter, 5],
  [Ritual_Slaughter, 6],
  [Ritual_Slaughter, 7],
  [Ritual_Slaughter, 8],
  [Ritual_Slaughter, 9],
  [Ritual_Slaughter, 10],
  [Ritual_Slaughter, 11],
  [Ritual_Slaughter, 12],
  [Ritual_Slaughter, 13],
  [Ritual_Slaughter, 14],
  [Oaths, 1],
  [Oaths, 2],
  [Oaths, 3],
  [Oaths, 4],
  [Oaths, 5],
  [Oaths, 6],
  [Oaths, 7],
  [Oaths, 8],
  [Oaths, 9],
  [Oaths, 10],
  [Oaths, 11],
  [Oaths, 12],
  [Vows, 1],
  [Vows, 2],
  [Vows, 3],
  [Vows, 4],
  [Vows, 5],
  [Vows, 6],
  [Vows, 7],
  [Vows, 8],
  [Vows, 9],
  [Vows, 10],
  [Vows, 11],
  [Vows, 12],
  [Vows, 13],
  [Nazariteship, 1],
  [Nazariteship, 2],
  [Nazariteship, 3],
  [Nazariteship, 4],
  [Nazariteship, 5],
  [Nazariteship, 6],
  [Nazariteship, 7],
  [Nazariteship, 8],
  [Nazariteship, 9],
  [Nazariteship, 10],
  [Appraisals_and_Devoted_Property, 1],
  [Appraisals_and_Devoted_Property, 2],
  [Appraisals_and_Devoted_Property, 3],
  [Appraisals_and_Devoted_Property, 4],
  [Appraisals_and_Devoted_Property, 5],
  [Appraisals_and_Devoted_Property, 6],
  [Appraisals_and_Devoted_Property, 7],
  [Appraisals_and_Devoted_Property, 8],
  [Diverse_Species, 1],
  [Diverse_Species, 2],
  [Diverse_Species, 3],
  [Diverse_Species, 4],
  [Diverse_Species, 5],
  [Diverse_Species, 6],
  [Diverse_Species, 7],
  [Diverse_Species, 8],
  [Diverse_Species, 9],
  [Diverse_Species, 10],
  [Gifts_to_the_Poor, 1],
  [Gifts_to_the_Poor, 2],
  [Gifts_to_the_Poor, 3],
  [Gifts_to_the_Poor, 4],
  [Gifts_to_the_Poor, 5],
  [Gifts_to_the_Poor, 6],
  [Gifts_to_the_Poor, 7],
  [Gifts_to_the_Poor, 8],
  [Gifts_to_the_Poor, 9],
  [Gifts_to_the_Poor, 10],
  [Heave_Offerings, 1],
  [Heave_Offerings, 2],
  [Heave_Offerings, 3],
  [Heave_Offerings, 4],
  [Heave_Offerings, 5],
  [Heave_Offerings, 6],
  [Heave_Offerings, 7],
  [Heave_Offerings, 8],
  [Heave_Offerings, 9],
  [Heave_Offerings, 10],
  [Heave_Offerings, 11],
  [Heave_Offerings, 12],
  [Heave_Offerings, 13],
  [Heave_Offerings, 14],
  [Heave_Offerings, 15],
  [Tithes, 1],
  [Tithes, 2],
  [Tithes, 3],
  [Tithes, 4],
  [Tithes, 5],
  [Tithes, 6],
  [Tithes, 7],
  [Tithes, 8],
  [Tithes, 9],
  [Tithes, 10],
  [Tithes, 11],
  [Tithes, 12],
  [Tithes, 13],
  [Tithes, 14],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 1],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 2],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 3],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 4],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 5],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 6],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 7],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 8],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 9],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 10],
  [Second_Tithes_and_Fourth_Year_s_Fruit, 11],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 1],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 2],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 3],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 4],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 5],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 6],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 7],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 8],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 9],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 10],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 11],
  [First_Fruits_and_other_Gifts_to_Priests_Outside_the_Sanctuary, 12],
  [Sabbatical_Year_and_the_Jubilee, 1],
  [Sabbatical_Year_and_the_Jubilee, 2],
  [Sabbatical_Year_and_the_Jubilee, 3],
  [Sabbatical_Year_and_the_Jubilee, 4],
  [Sabbatical_Year_and_the_Jubilee, 5],
  [Sabbatical_Year_and_the_Jubilee, 6],
  [Sabbatical_Year_and_the_Jubilee, 7],
  [Sabbatical_Year_and_the_Jubilee, 8],
  [Sabbatical_Year_and_the_Jubilee, 9],
  [Sabbatical_Year_and_the_Jubilee, 10],
  [Sabbatical_Year_and_the_Jubilee, 11],
  [Sabbatical_Year_and_the_Jubilee, 12],
  [Sabbatical_Year_and_the_Jubilee, 13],
  [The_Chosen_Temple, 1],
  [The_Chosen_Temple, 2],
  [The_Chosen_Temple, 3],
  [The_Chosen_Temple, 4],
  [The_Chosen_Temple, 5],
  [The_Chosen_Temple, 6],
  [The_Chosen_Temple, 7],
  [The_Chosen_Temple, 8],
  [Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein, 1],
  [Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein, 2],
  [Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein, 3],
  [Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein, 4],
  [Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein, 5],
  [Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein, 6],
  [Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein, 7],
  [Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein, 8],
  [Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein, 9],
  [Vessels_of_the_Sanctuary_and_Those_who_Serve_Therein, 10],
  [Admission_into_the_Sanctuary, 1],
  [Admission_into_the_Sanctuary, 2],
  [Admission_into_the_Sanctuary, 3],
  [Admission_into_the_Sanctuary, 4],
  [Admission_into_the_Sanctuary, 5],
  [Admission_into_the_Sanctuary, 6],
  [Admission_into_the_Sanctuary, 7],
  [Admission_into_the_Sanctuary, 8],
  [Admission_into_the_Sanctuary, 9],
  [Things_Forbidden_on_the_Altar, 1],
  [Things_Forbidden_on_the_Altar, 2],
  [Things_Forbidden_on_the_Altar, 3],
  [Things_Forbidden_on_the_Altar, 4],
  [Things_Forbidden_on_the_Altar, 5],
  [Things_Forbidden_on_the_Altar, 6],
  [Things_Forbidden_on_the_Altar, 7],
  [Sacrificial_Procedure, 1],
  [Sacrificial_Procedure, 2],
  [Sacrificial_Procedure, 3],
  [Sacrificial_Procedure, 4],
  [Sacrificial_Procedure, 5],
  [Sacrificial_Procedure, 6],
  [Sacrificial_Procedure, 7],
  [Sacrificial_Procedure, 8],
  [Sacrificial_Procedure, 9],
  [Sacrificial_Procedure, 10],
  [Sacrificial_Procedure, 11],
  [Sacrificial_Procedure, 12],
  [Sacrificial_Procedure, 13],
  [Sacrificial_Procedure, 14],
  [Sacrificial_Procedure, 15],
  [Sacrificial_Procedure, 16],
  [Sacrificial_Procedure, 17],
  [Sacrificial_Procedure, 18],
  [Sacrificial_Procedure, 19],
  [Daily_Offerings_and_Additional_Offerings, 1],
  [Daily_Offerings_and_Additional_Offerings, 2],
  [Daily_Offerings_and_Additional_Offerings, 3],
  [Daily_Offerings_and_Additional_Offerings, 4],
  [Daily_Offerings_and_Additional_Offerings, 5],
  [Daily_Offerings_and_Additional_Offerings, 6],
  [Daily_Offerings_and_Additional_Offerings, 7],
  [Daily_Offerings_and_Additional_Offerings, 8],
  [Daily_Offerings_and_Additional_Offerings, 9],
  [Daily_Offerings_and_Additional_Offerings, 10],
  [Sacrifices_Rendered_Unfit, 1],
  [Sacrifices_Rendered_Unfit, 2],
  [Sacrifices_Rendered_Unfit, 3],
  [Sacrifices_Rendered_Unfit, 4],
  [Sacrifices_Rendered_Unfit, 5],
  [Sacrifices_Rendered_Unfit, 6],
  [Sacrifices_Rendered_Unfit, 7],
  [Sacrifices_Rendered_Unfit, 8],
  [Sacrifices_Rendered_Unfit, 9],
  [Sacrifices_Rendered_Unfit, 10],
  [Sacrifices_Rendered_Unfit, 11],
  [Sacrifices_Rendered_Unfit, 12],
  [Sacrifices_Rendered_Unfit, 13],
  [Sacrifices_Rendered_Unfit, 14],
  [Sacrifices_Rendered_Unfit, 15],
  [Sacrifices_Rendered_Unfit, 16],
  [Sacrifices_Rendered_Unfit, 17],
  [Sacrifices_Rendered_Unfit, 18],
  [Sacrifices_Rendered_Unfit, 19],
  [Service_on_the_Day_of_Atonement, 1],
  [Service_on_the_Day_of_Atonement, 2],
  [Service_on_the_Day_of_Atonement, 3],
  [Service_on_the_Day_of_Atonement, 4],
  [Service_on_the_Day_of_Atonement, 5],
  [Trespass, 1],
  [Trespass, 2],
  [Trespass, 3],
  [Trespass, 4],
  [Trespass, 5],
  [Trespass, 6],
  [Trespass, 7],
  [Trespass, 8],
  [Paschal_Offering, 1],
  [Paschal_Offering, 2],
  [Paschal_Offering, 3],
  [Paschal_Offering, 4],
  [Paschal_Offering, 5],
  [Paschal_Offering, 6],
  [Paschal_Offering, 7],
  [Paschal_Offering, 8],
  [Paschal_Offering, 9],
  [Paschal_Offering, 10],
  [Festival_Offering, 1],
  [Festival_Offering, 2],
  [Festival_Offering, 3],
  [Firstlings, 1],
  [Firstlings, 2],
  [Firstlings, 3],
  [Firstlings, 4],
  [Firstlings, 5],
  [Firstlings, 6],
  [Firstlings, 7],
  [Firstlings, 8],
  [Offerings_for_Unintentional_Transgressions, 1],
  [Offerings_for_Unintentional_Transgressions, 2],
  [Offerings_for_Unintentional_Transgressions, 3],
  [Offerings_for_Unintentional_Transgressions, 4],
  [Offerings_for_Unintentional_Transgressions, 5],
  [Offerings_for_Unintentional_Transgressions, 6],
  [Offerings_for_Unintentional_Transgressions, 7],
  [Offerings_for_Unintentional_Transgressions, 8],
  [Offerings_for_Unintentional_Transgressions, 9],
  [Offerings_for_Unintentional_Transgressions, 10],
  [Offerings_for_Unintentional_Transgressions, 11],
  [Offerings_for_Unintentional_Transgressions, 12],
  [Offerings_for_Unintentional_Transgressions, 13],
  [Offerings_for_Unintentional_Transgressions, 14],
  [Offerings_for_Unintentional_Transgressions, 15],
  [Offerings_for_Those_with_Incomplete_Atonement, 1],
  [Offerings_for_Those_with_Incomplete_Atonement, 2],
  [Offerings_for_Those_with_Incomplete_Atonement, 3],
  [Offerings_for_Those_with_Incomplete_Atonement, 4],
  [Offerings_for_Those_with_Incomplete_Atonement, 5],
  [Substitution, 1],
  [Substitution, 2],
  [Substitution, 3],
  [Substitution, 4],
  [Defilement_by_a_Corpse, 1],
  [Defilement_by_a_Corpse, 2],
  [Defilement_by_a_Corpse, 3],
  [Defilement_by_a_Corpse, 4],
  [Defilement_by_a_Corpse, 5],
  [Defilement_by_a_Corpse, 6],
  [Defilement_by_a_Corpse, 7],
  [Defilement_by_a_Corpse, 8],
  [Defilement_by_a_Corpse, 9],
  [Defilement_by_a_Corpse, 10],
  [Defilement_by_a_Corpse, 11],
  [Defilement_by_a_Corpse, 12],
  [Defilement_by_a_Corpse, 13],
  [Defilement_by_a_Corpse, 14],
  [Defilement_by_a_Corpse, 15],
  [Defilement_by_a_Corpse, 16],
  [Defilement_by_a_Corpse, 17],
  [Defilement_by_a_Corpse, 18],
  [Defilement_by_a_Corpse, 19],
  [Defilement_by_a_Corpse, 20],
  [Defilement_by_a_Corpse, 21],
  [Defilement_by_a_Corpse, 22],
  [Defilement_by_a_Corpse, 23],
  [Defilement_by_a_Corpse, 24],
  [Defilement_by_a_Corpse, 25],
  [Red_Heifer, 1],
  [Red_Heifer, 2],
  [Red_Heifer, 3],
  [Red_Heifer, 4],
  [Red_Heifer, 5],
  [Red_Heifer, 6],
  [Red_Heifer, 7],
  [Red_Heifer, 8],
  [Red_Heifer, 9],
  [Red_Heifer, 10],
  [Red_Heifer, 11],
  [Red_Heifer, 12],
  [Red_Heifer, 13],
  [Red_Heifer, 14],
  [Red_Heifer, 15],
  [Defilement_by_Leprosy, 1],
  [Defilement_by_Leprosy, 2],
  [Defilement_by_Leprosy, 3],
  [Defilement_by_Leprosy, 4],
  [Defilement_by_Leprosy, 5],
  [Defilement_by_Leprosy, 6],
  [Defilement_by_Leprosy, 7],
  [Defilement_by_Leprosy, 8],
  [Defilement_by_Leprosy, 9],
  [Defilement_by_Leprosy, 10],
  [Defilement_by_Leprosy, 11],
  [Defilement_by_Leprosy, 12],
  [Defilement_by_Leprosy, 13],
  [Defilement_by_Leprosy, 14],
  [Defilement_by_Leprosy, 15],
  [Defilement_by_Leprosy, 16],
  [Those_Who_Defile_Bed_or_Seat, 1],
  [Those_Who_Defile_Bed_or_Seat, 2],
  [Those_Who_Defile_Bed_or_Seat, 3],
  [Those_Who_Defile_Bed_or_Seat, 4],
  [Those_Who_Defile_Bed_or_Seat, 5],
  [Those_Who_Defile_Bed_or_Seat, 6],
  [Those_Who_Defile_Bed_or_Seat, 7],
  [Those_Who_Defile_Bed_or_Seat, 8],
  [Those_Who_Defile_Bed_or_Seat, 9],
  [Those_Who_Defile_Bed_or_Seat, 10],
  [Those_Who_Defile_Bed_or_Seat, 11],
  [Those_Who_Defile_Bed_or_Seat, 12],
  [Those_Who_Defile_Bed_or_Seat, 13],
  [Other_Sources_of_Defilement, 1],
  [Other_Sources_of_Defilement, 2],
  [Other_Sources_of_Defilement, 3],
  [Other_Sources_of_Defilement, 4],
  [Other_Sources_of_Defilement, 5],
  [Other_Sources_of_Defilement, 6],
  [Other_Sources_of_Defilement, 7],
  [Other_Sources_of_Defilement, 8],
  [Other_Sources_of_Defilement, 9],
  [Other_Sources_of_Defilement, 10],
  [Other_Sources_of_Defilement, 11],
  [Other_Sources_of_Defilement, 12],
  [Other_Sources_of_Defilement, 13],
  [Other_Sources_of_Defilement, 14],
  [Other_Sources_of_Defilement, 15],
  [Other_Sources_of_Defilement, 16],
  [Other_Sources_of_Defilement, 17],
  [Other_Sources_of_Defilement, 18],
  [Other_Sources_of_Defilement, 19],
  [Other_Sources_of_Defilement, 20],
  [Defilement_of_Foods, 1],
  [Defilement_of_Foods, 2],
  [Defilement_of_Foods, 3],
  [Defilement_of_Foods, 4],
  [Defilement_of_Foods, 5],
  [Defilement_of_Foods, 6],
  [Defilement_of_Foods, 7],
  [Defilement_of_Foods, 8],
  [Defilement_of_Foods, 9],
  [Defilement_of_Foods, 10],
  [Defilement_of_Foods, 11],
  [Defilement_of_Foods, 12],
  [Defilement_of_Foods, 13],
  [Defilement_of_Foods, 14],
  [Defilement_of_Foods, 15],
  [Defilement_of_Foods, 16],
  [Vessels, 1],
  [Vessels, 2],
  [Vessels, 3],
  [Vessels, 4],
  [Vessels, 5],
  [Vessels, 6],
  [Vessels, 7],
  [Vessels, 8],
  [Vessels, 9],
  [Vessels, 10],
  [Vessels, 11],
  [Vessels, 12],
  [Vessels, 13],
  [Vessels, 14],
  [Vessels, 15],
  [Vessels, 16],
  [Vessels, 17],
  [Vessels, 18],
  [Vessels, 19],
  [Vessels, 20],
  [Vessels, 21],
  [Vessels, 22],
  [Vessels, 23],
  [Vessels, 24],
  [Vessels, 25],
  [Vessels, 26],
  [Vessels, 27],
  [Vessels, 28],
  [Immersion_Pools, 1],
  [Immersion_Pools, 2],
  [Immersion_Pools, 3],
  [Immersion_Pools, 4],
  [Immersion_Pools, 5],
  [Immersion_Pools, 6],
  [Immersion_Pools, 7],
  [Immersion_Pools, 8],
  [Immersion_Pools, 9],
  [Immersion_Pools, 10],
  [Immersion_Pools, 11],
  [Damages_to_Property, 1],
  [Damages_to_Property, 2],
  [Damages_to_Property, 3],
  [Damages_to_Property, 4],
  [Damages_to_Property, 5],
  [Damages_to_Property, 6],
  [Damages_to_Property, 7],
  [Damages_to_Property, 8],
  [Damages_to_Property, 9],
  [Damages_to_Property, 10],
  [Damages_to_Property, 11],
  [Damages_to_Property, 12],
  [Damages_to_Property, 13],
  [Damages_to_Property, 14],
  [Theft, 1],
  [Theft, 2],
  [Theft, 3],
  [Theft, 4],
  [Theft, 5],
  [Theft, 6],
  [Theft, 7],
  [Theft, 8],
  [Theft, 9],
  [Robbery_and_Lost_Property, 1],
  [Robbery_and_Lost_Property, 2],
  [Robbery_and_Lost_Property, 3],
  [Robbery_and_Lost_Property, 4],
  [Robbery_and_Lost_Property, 5],
  [Robbery_and_Lost_Property, 6],
  [Robbery_and_Lost_Property, 7],
  [Robbery_and_Lost_Property, 8],
  [Robbery_and_Lost_Property, 9],
  [Robbery_and_Lost_Property, 10],
  [Robbery_and_Lost_Property, 11],
  [Robbery_and_Lost_Property, 12],
  [Robbery_and_Lost_Property, 13],
  [Robbery_and_Lost_Property, 14],
  [Robbery_and_Lost_Property, 15],
  [Robbery_and_Lost_Property, 16],
  [Robbery_and_Lost_Property, 17],
  [Robbery_and_Lost_Property, 18],
  [One_Who_Injures_a_Person_or_Property, 1],
  [One_Who_Injures_a_Person_or_Property, 2],
  [One_Who_Injures_a_Person_or_Property, 3],
  [One_Who_Injures_a_Person_or_Property, 4],
  [One_Who_Injures_a_Person_or_Property, 5],
  [One_Who_Injures_a_Person_or_Property, 6],
  [One_Who_Injures_a_Person_or_Property, 7],
  [One_Who_Injures_a_Person_or_Property, 8],
  [Murderer_and_the_Preservation_of_Life, 1],
  [Murderer_and_the_Preservation_of_Life, 2],
  [Murderer_and_the_Preservation_of_Life, 3],
  [Murderer_and_the_Preservation_of_Life, 4],
  [Murderer_and_the_Preservation_of_Life, 5],
  [Murderer_and_the_Preservation_of_Life, 6],
  [Murderer_and_the_Preservation_of_Life, 7],
  [Murderer_and_the_Preservation_of_Life, 8],
  [Murderer_and_the_Preservation_of_Life, 9],
  [Murderer_and_the_Preservation_of_Life, 10],
  [Murderer_and_the_Preservation_of_Life, 11],
  [Murderer_and_the_Preservation_of_Life, 12],
  [Murderer_and_the_Preservation_of_Life, 13],
  [Sales, 1],
  [Sales, 2],
  [Sales, 3],
  [Sales, 4],
  [Sales, 5],
  [Sales, 6],
  [Sales, 7],
  [Sales, 8],
  [Sales, 9],
  [Sales, 10],
  [Sales, 11],
  [Sales, 12],
  [Sales, 13],
  [Sales, 14],
  [Sales, 15],
  [Sales, 16],
  [Sales, 17],
  [Sales, 18],
  [Sales, 19],
  [Sales, 20],
  [Sales, 21],
  [Sales, 22],
  [Sales, 23],
  [Sales, 24],
  [Sales, 25],
  [Sales, 26],
  [Sales, 27],
  [Sales, 28],
  [Sales, 29],
  [Sales, 30],
  [Ownerless_Property_and_Gifts, 1],
  [Ownerless_Property_and_Gifts, 2],
  [Ownerless_Property_and_Gifts, 3],
  [Ownerless_Property_and_Gifts, 4],
  [Ownerless_Property_and_Gifts, 5],
  [Ownerless_Property_and_Gifts, 6],
  [Ownerless_Property_and_Gifts, 7],
  [Ownerless_Property_and_Gifts, 8],
  [Ownerless_Property_and_Gifts, 9],
  [Ownerless_Property_and_Gifts, 10],
  [Ownerless_Property_and_Gifts, 11],
  [Ownerless_Property_and_Gifts, 12],
  [Neighbors, 1],
  [Neighbors, 2],
  [Neighbors, 3],
  [Neighbors, 4],
  [Neighbors, 6],
  [Neighbors, 7],
  [Neighbors, 8],
  [Neighbors, 9],
  [Neighbors, 10],
  [Neighbors, 11],
  [Neighbors, 12],
  [Neighbors, 13],
  [Neighbors, 14],
  [Agents_and_Partners, 1],
  [Agents_and_Partners, 2],
  [Agents_and_Partners, 3],
  [Agents_and_Partners, 4],
  [Agents_and_Partners, 5],
  [Agents_and_Partners, 6],
  [Agents_and_Partners, 7],
  [Agents_and_Partners, 8],
  [Agents_and_Partners, 9],
  [Agents_and_Partners, 10],
  [Slaves, 1],
  [Slaves, 2],
  [Slaves, 3],
  [Slaves, 4],
  [Slaves, 5],
  [Slaves, 6],
  [Slaves, 7],
  [Slaves, 8],
  [Slaves, 9],
  [Hiring, 1],
  [Hiring, 2],
  [Hiring, 3],
  [Hiring, 4],
  [Hiring, 5],
  [Hiring, 6],
  [Hiring, 7],
  [Hiring, 8],
  [Hiring, 9],
  [Hiring, 10],
  [Hiring, 11],
  [Hiring, 12],
  [Hiring, 13],
  [Borrowing_and_Deposit, 1],
  [Borrowing_and_Deposit, 2],
  [Borrowing_and_Deposit, 3],
  [Borrowing_and_Deposit, 4],
  [Borrowing_and_Deposit, 5],
  [Borrowing_and_Deposit, 6],
  [Borrowing_and_Deposit, 7],
  [Borrowing_and_Deposit, 8],
  [Creditor_and_Debtor, 1],
  [Creditor_and_Debtor, 2],
  [Creditor_and_Debtor, 3],
  [Creditor_and_Debtor, 4],
  [Creditor_and_Debtor, 5],
  [Creditor_and_Debtor, 6],
  [Creditor_and_Debtor, 7],
  [Creditor_and_Debtor, 8],
  [Creditor_and_Debtor, 9],
  [Creditor_and_Debtor, 10],
  [Creditor_and_Debtor, 11],
  [Creditor_and_Debtor, 12],
  [Creditor_and_Debtor, 13],
  [Creditor_and_Debtor, 14],
  [Creditor_and_Debtor, 15],
  [Creditor_and_Debtor, 16],
  [Creditor_and_Debtor, 17],
  [Creditor_and_Debtor, 18],
  [Creditor_and_Debtor, 19],
  [Creditor_and_Debtor, 20],
  [Creditor_and_Debtor, 21],
  [Creditor_and_Debtor, 22],
  [Creditor_and_Debtor, 23],
  [Creditor_and_Debtor, 24],
  [Creditor_and_Debtor, 25],
  [Creditor_and_Debtor, 26],
  [Creditor_and_Debtor, 27],
  [Plaintiff_and_Defendant, 1],
  [Plaintiff_and_Defendant, 2],
  [Plaintiff_and_Defendant, 3],
  [Plaintiff_and_Defendant, 4],
  [Plaintiff_and_Defendant, 5],
  [Plaintiff_and_Defendant, 6],
  [Plaintiff_and_Defendant, 7],
  [Plaintiff_and_Defendant, 8],
  [Plaintiff_and_Defendant, 9],
  [Plaintiff_and_Defendant, 10],
  [Plaintiff_and_Defendant, 11],
  [Plaintiff_and_Defendant, 12],
  [Plaintiff_and_Defendant, 13],
  [Plaintiff_and_Defendant, 14],
  [Plaintiff_and_Defendant, 15],
  [Plaintiff_and_Defendant, 16],
  [Inheritances, 1],
  [Inheritances, 2],
  [Inheritances, 3],
  [Inheritances, 4],
  [Inheritances, 5],
  [Inheritances, 6],
  [Inheritances, 7],
  [Inheritances, 8],
  [Inheritances, 9],
  [Inheritances, 10],
  [Inheritances, 11],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 1],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 2],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 3],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 4],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 5],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 6],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 7],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 8],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 9],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 10],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 11],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 12],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 13],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 14],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 15],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 16],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 17],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 18],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 19],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 20],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 21],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 22],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 23],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 24],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 25],
  [The_Sanhedrin_and_the_Penalties_within_their_Jurisdiction, 26],
  [Testimony, 1],
  [Testimony, 2],
  [Testimony, 3],
  [Testimony, 4],
  [Testimony, 5],
  [Testimony, 6],
  [Testimony, 7],
  [Testimony, 8],
  [Testimony, 9],
  [Testimony, 10],
  [Testimony, 11],
  [Testimony, 12],
  [Testimony, 13],
  [Testimony, 14],
  [Testimony, 15],
  [Testimony, 16],
  [Testimony, 17],
  [Testimony, 18],
  [Testimony, 19],
  [Testimony, 20],
  [Testimony, 21],
  [Testimony, 22],
  [Rebels, 1],
  [Rebels, 2],
  [Rebels, 3],
  [Rebels, 4],
  [Rebels, 5],
  [Rebels, 6],
  [Rebels, 7],
  [Mourning, 1],
  [Mourning, 2],
  [Mourning, 3],
  [Mourning, 4],
  [Mourning, 5],
  [Mourning, 6],
  [Mourning, 7],
  [Mourning, 8],
  [Mourning, 9],
  [Mourning, 10],
  [Mourning, 11],
  [Mourning, 12],
  [Mourning, 13],
  [Mourning, 14],
  [Kings_and_Wars, 1],
  [Kings_and_Wars, 2],
  [Kings_and_Wars, 3],
  [Kings_and_Wars, 4],
  [Kings_and_Wars, 5],
  [Kings_and_Wars, 6],
  [Kings_and_Wars, 7],
  [Kings_and_Wars, 8],
  [Kings_and_Wars, 9],
  [Kings_and_Wars, 10],
  [Kings_and_Wars, 11],
  [Kings_and_Wars, 12],
];
